# Generated by Django 3.2.5 on 2021-07-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=16)),
                ('BookName', models.CharField(max_length=20)),
                ('Operation_needed', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default='def', max_length=15),
            preserve_default=False,
        ),
    ]
