# Generated by Django 3.2.5 on 2021-07-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210714_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Publish_year',
            field=models.DecimalField(decimal_places=0, default=200, max_digits=4),
            preserve_default=False,
        ),
    ]
