# Generated by Django 3.2.5 on 2021-07-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_book_publish_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Name',
            field=models.CharField(max_length=40),
        ),
    ]
